### PR TITLE
use secure agent pool

### LINKED ISSUE #624: Migrate Pipeline off Retail Pools
For internal security reasons it is needed to migrate to internal machine host pool.
Deadline is 8th of March 2022.

(UPD: view Email with detailed explanation)

### PR DESCRIPTION
**Pull request by DeagleGross**
Closes #624

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
LGTM

**Comment by tomkerkhove** [comment]
@DeagleGross It looks like it can't find that VM image:
> ##[warning]An image label with the label VSEngSS-MicroBuild2022-1ES does not exist.

**Comment by DeagleGross** [comment]
Done by @adrianhall already, so abandoning this PR and closing #624

**Pull request closed without merging**
