### PR TITLE
Azure DevOps Automation Enhancements (Creator Utility)

### PR DESCRIPTION
**Pull request by punitganshani**
## Environment Variables

Enabled substitution of Environment Variables in the `filenames` and `YAML` file. This helps in automating the build pipeline 

### YAML usage

```
apis:
    - name: PetStore
      type: http
      description: Pet Store
      openApiSpec: %PetStore%
```

### Azure DevOps Variables

image

## OpenAPI URL Parameter in API configuration

If OpenAPI URL is remote link, a parameter will be added so that OpenAPI URL can be overridden during deployment automation

image

## Folder Path

Creation of folder when output folder doesn't exist.

### CODE REVIEW

**Comment by MichalKosowski** [comment]
Hi,

Why not use the DevOps for substitution? I am using replace tokens tasks (as for any configuration files). That works perfectly without modifying the tool. Personally I think that it is better to make this that way than making a tool too big.

**Comment by miaojiang** [comment]
I agree with @MichalKosowski. Closing this PR for now.

**Comment by JohnKozell** [comment]
"Replace Tokens" task doesn't look like it's available in the new Yaml pipelines, so this feature may be appropriate after all. Alternatively expose `outputLocation` to the command line.

**Comment by bremnes** [comment]
@JohnKozell Can you share the yaml snippet you are trying to use? As far as I know all tasks that work in the "classical editor"/gui should work in yaml as well.

**Comment by JohnKozell** [comment]
@bremnes - good question, looks like there are at least 4 token replace tasks in the market place. The only native one seems to be "File Transform" which doesn't work on yaml files (my case). I based my availability claim on the list that came up when in the textual pipeline editor, none looked like they were any derivation of "replace tokens". What yaml task did you have in mind?

**Comment by bremnes** [comment]
@JohnKozell, here's an example of what I've been using, the ["Replace tokens" extension](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens) by Guillaume Rouchon
```yaml
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens in **/appsettings.json'
  inputs:
    rootDirectory: 'relative/path/to/solution'
    targetFiles: '**/appsettings.json'
    tokenPrefix: '__'
    tokenSuffix: '__'
```
(This task replaces values in files matching the pattern with variable values. So for instance `__MyVariable__` is replace with a variable called `MyVariable`.)

**Pull request closed without merging**
