### PR TITLE
upgrade to dotnet core 3.1

### PR DESCRIPTION
**Pull request by thandotettey**
upgraded the project to dotnet core 3.1
added a docker file to package the tool so that developers can use it without requiring dotnet 3.1 as a dependency

### CODE REVIEW

**Comment by rabrahamOpti** [comment]
I'm running into this issue when trying to build the extractor into a self-contained executable https://github.com/dotnet/sdk/issues/2505 

I believe upgrading the project to 3.1 will address that.

**Comment by KaiWalter** [comment]
@vladvino @miaojiang anything holding us back from bumping up to .NET Core 3.1?

**Comment by rabrahamOpti** [comment]
> 
> 
> @rabrahamOpti have you verified that everything works well after you have upgraded the dotnet version?

I haven't tested this branch (and unfortunately don't currently have the bandwidth to., I just wanted to express one reason why this update would be beneficial.

**Comment by KaiWalter** [comment]
@RupengLiu I was using the toolkit with a .NET Core 3.1 build the past weeks, extracting several APIs and experiencing no regressions

**Comment by RupengLiu** [comment]
Cool, commit merged!

**Pull request merged**
