### PR TITLE
Make approvalRequired and subscriptionsLimit nullable

### PR DESCRIPTION
**Pull request by Frederic-roamler**
When I deploy the extracted templates to my APIM instance I get the following error:

> Cannot provide values for approvalRequired and subscriptionsLimit when subscriptionRequired is set to false in the request payload

Changing the properties to nullable types solves the problem

### CODE REVIEW

**Comment by ybelMekk** [comment]
Im in for this one

**Comment by miaojiang** [comment]
Thanks for the PR. I ran into the same issue and tried to fix it by #207.

I think the changes in this PR does not solve all potential cases. For example, if subscriptionRequired is false and approvalRequired is true in the YAML file, the generated template would still contain approvalRequired, which would not be accepted by Azure Resource Manager.

**Comment by Frederic-roamler** [comment]
Thanks for your review @lucashuet93. Until now I only used the extractor, but now I also updated the code for the creator.

**Comment by miaojiang** [comment]
@Frederic-roamler thanks for your contribution! We appreciate it.

**Pull request merged**
