### PR TITLE
fix for missing PolicyXMLBaseUrl param from extractor master template

### PR DESCRIPTION
**Pull request by UmairSyed**
Bug fix for:
- Master template generated by the extractor not passing the PolicyXMLBaseUrl as a param to child templates that is causing errors at deployment time.

### CODE REVIEW

**Comment by bremnes** [comment]
@UmairSyed, did you mean to add the last three commits to this pull request? They seem somewhat specific for your personal scenario.

**Comment by UmairSyed** [comment]
No. I can undo the last twp commits re .sh and .cmd.

**Comment by UmairSyed** [comment]
I have reverted the unwanted commits. Please proceed with the approval.

**Comment by mzrzz3** [comment]
When will this branch be merged? The bug still seems to exist and the fix is required.

**Comment by RupengLiu** [comment]
nice catch @UmairSyed

**Pull request merged**
