### PR TITLE
Added Groups extractor

### PR DESCRIPTION
**Pull request by zapiko**
Added Microsoft.ApiManagement/service/groups extraction

### CODE REVIEW

**Comment by zapiko** [comment]
@microsoftopensource, could you change the pipeline image from ubuntu16 to ubuntu-latest?

**Comment by zapiko** [comment]
@odaibert @lucashuet93 @miaojiang please, check

**Comment by zapiko** [comment]
@tomkerkhove ;)

**Comment by adrianhall** [comment]
@zapiko - it's me now - I'll get on this today.

**Comment by zapiko** [comment]
@adrianhall Can I do something to help with this?

**Comment by adrianhall** [comment]
Hey @cmendible - ack on the request.  I'm working on getting an engineer for this.

**Comment by adrianhall** [comment]
Following up - we've been in a lull on work for this.  Work will be restarting mid-next month.  I've asked that the PRs be given priority over new feature work.  More news when I have it.

**Comment by zapiko** [comment]
@adrianhall @DeagleGross Can I help with something?

**Comment by DeagleGross** [comment]
Hello, @zapiko. Thanks for contribution!
Currently we are working on refactoring the resource-kit repo ([major-repo-refactoring](https://github.com/Azure/azure-api-management-devops-resource-kit/tree/major-repo-refactoring)), so I have implemented groups extractor and made a PR to merge changes in that branch. Please, view the [PullRequest: implement groups extractor](https://github.com/Azure/azure-api-management-devops-resource-kit/pull/641)

We will be releasing refactored resource-kit soon, so dont worry - we won't lose your changes.
You can track progress regarding the release on [GitHub Board](https://github.com/Azure/azure-api-management-devops-resource-kit/projects/1).

Closing this pull request for now, but feel free to reopen it if you have any questions/concerns :)

**Pull request closed without merging**
