### PR TITLE
Allow to parametrize serviceUrl

### PR DESCRIPTION
**Pull request by lurumad**
### What this PR does / why we need it:

This PR add support to parametrize serviceUrl in ARM templates in order to be able to set by environemt from a CI/CD pipeline.

Please make sure you've completed the relevant tasks for this PR, out of the following list:

 - [X] Code compiles correctly
 - [X] Created/updated tests
 - [X] Unit tests passing
 - [X] End-to-end tests passing
 - [ ] Add documentation
 - [ ] Provided sample for the feature

If you don't set serviceUrl property in yml file or you don't pass --backendurlconfigFile in create commandline arguments:

```powershell
apim-templates create --configFile apim.yml
```

image

When you set serviceUrl property in yml file or you pass --backendurlconfigFile in create commandline arguments:

```powershell
apim-templates create --configFile apim.yml --backendurlconfigFile ..\serviceUrl.json
```

image

Regards!

### CODE REVIEW

**Comment by ThomasBleijendaal** [comment]
I think we should align with what the Extractor outputs when `paramServiceUrl` is set to `true` in the extractor config. It creates a `serviceUrl` as object. In stead of `[parameters('serviceUrl')] it generates it as `[parameters('serviceUrl').nameofyourapi]`.

This will work better when you link Creator and Extractor templates into a single master ARM template.

**Comment by lurumad** [comment]
Hi @ThomasBleijendaal 

I'll take a look at extractor config and  I'll try to align with my PR.

Thanks!

**Comment by ThomasBleijendaal** [comment]
Hi @lurumad,

I took a shot at the implementation (also based on your work) since I needed similar behavior for a project, you could take a look at: https://github.com/Azure/azure-api-management-devops-resource-kit/commit/de904dcb8667b0087a9caa1453fc43c7638dd311 and https://github.com/Azure/azure-api-management-devops-resource-kit/commit/00cd91aa45168a326fdd47e51a1c607807e65735 as implements the `serviceUrl` as an object.

I hope this can help.

Cheers.

**Comment by lurumad** [comment]
Hi @ThomasBleijendaal 

I made the change!

@RupengLiu Would you mind to review the PR?

Regards!

**Pull request merged**
